x-services-template:
  api: &api
    image: juanlimalf/api-payment_processor-rinha_backend_2025:redis
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - api
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 85M

  worker: &worker
    image: juanlimalf/worker-payment_processor-rinha_backend_2025:redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - api
      - payment-processor
    depends_on:
      - redis
      - api
      - api2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 90M

services:
  api:
    <<: *api
    container_name: api

  api2:
    <<: *api
    container_name: api2

  worker:
    <<: *worker
    container_name: worker

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - api
    depends_on:
      - api
      - api2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 30M

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - api
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 60M

networks:
  api:
    driver: bridge
  payment-processor:
    external: true
