x-services-template:
  api: &api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080

    networks:
      - api
    
    deploy:
      resources:
        limits:
          cpus: '0.28'
          memory: 78M

  worker: &worker
    <<: *api
    command: celery -A api.config.celery_app worker --loglevel=info --concurrency=1
    networks:
      - api
      - payment-processor

    deploy:
      resources:
        limits:
          cpus: '0.28'
          memory: 76M

services:
  api:
    <<: *api
    container_name: api

  api2:
    <<: *api
    container_name: api2

  worker:
    <<: *worker
    container_name: worker

  worker2:
    <<: *worker
    container_name: worker2

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - api
    depends_on:
      - api
      - api2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.19'
          memory: 18M

  redis:
    image: redis:8.0.3
    container_name: redis
    restart: unless-stopped
    networks:
      - api
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.19'
          memory: 24M


networks:
  api:
    driver: bridge
  payment-processor:
    external: true