x-services-template:
  api: &api
    image: juanlimalf/api-payment_processor-rinha_backend_2025
    # build:
    #   context: ./api
    #   dockerfile: Dockerfile
    # volumes:
    #   - ./api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --loop uvloop --http httptools --workers 1 --no-access-log
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - api
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 55M

  worker: &worker
    image: juanlimalf/worker-payment_processor-rinha_backend_2025
    # build:
    #   context: ./worker
    #   dockerfile: Dockerfile
    # volumes:
    #   - ./worker:/app
    command: python main.py
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - api
      - payment-processor
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_started
      api2:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 55M

services:
  api:
    <<: *api
    container_name: api

  api2:
    <<: *api
    container_name: api2
    
  worker:
    <<: *worker
    container_name: worker

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - api
    depends_on:
      - api
      - api2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 30M

  postgres:
    command: ["postgres", "-c", "max_connections=500"]
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 145M
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  api:
    driver: bridge
  payment-processor:
    external: true