services:
  api: &api
    container_name: api
    image: juanlimalf/api-payment_processor-rinha_backend_2025:redis-1.1
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - NUM_WORKERS=15
      - LOG_LEVEL=ERROR
    networks:
      - api
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 75M

  api2:
    <<: *api
    container_name: api2

  api3:
    <<: *api
    container_name: api3

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - api
    depends_on:
      - api
      - api2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 30M

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - api
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 95M

networks:
  api:
    driver: bridge
  payment-processor:
    external: true
