x-services-template:
  api: &api
    image: juanlimalf/api-payment_processor-rinha_backend_2025
    # build:
    #   context: ./api
    #   dockerfile: Dockerfile
    # volumes:
    #   - ./api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --loop uvloop --http httptools --workers 1 --no-access-log
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - api
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 50M

  worker: &worker
    image: juanlimalf/worker-payment_processor-rinha_backend_2025
    # build:
    #   context: ./worker
    #   dockerfile: Dockerfile
    # volumes:
    #   - ./worker:/app
    command: python main.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - api
      - payment-processor
    depends_on:
      - redis
      - postgres
      - api
      - api2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 65M

services:
  api:
    <<: *api
    container_name: api
  api2:
    <<: *api
    container_name: api2

  worker:
    <<: *worker
    container_name: worker
  worker2:
    <<: *worker
    container_name: worker2

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - api
    depends_on:
      - api
      - api2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 20M

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - api
    command: redis-server --appendonly yes --appendfsync everysec
    # ports:
    #   - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 55M

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - api
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 40M 

networks:
  api:
    driver: bridge
  payment-processor:
    external: true