from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DatabaseProtocol(Protocol):
    def get_engine(self) -> Any: ...

    def get_session(self): ...

    def __enter__(self) -> Any: ...

    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
